### ISSUE TITLE
Unlist package from NuGet

### ISSUE THREAD

**Issue by zvirja** [MarkStruik/AutoFixture.AutoMoq.AutoSetup#2]
Hi @MarkStruik,

I've found that his repository belongs to the [AutoFixture.AutoMoq.AutoSetup](https://www.nuget.org/packages/AutoFixture.AutoMoq.AutoSetup/) NuGet package.

The package name you used is a bit confusing as it looks like it's a part of the AutoFixture package family. Also I've found that this package provides feature that is a part of the AutoFixture now, so it's no longer required.

Would you be fine to unlist the package on NuGet, so it's no longer visible in the search? That would cause less confusion to our new clients.

If you would like to contribute extensions to the AutoFixture in future, please use the `AutoFixture.Community` package prefix - the ownership will be much clear.

Thanks a lot for your time!

**Comment by MarkStruik** [comment]
It has been a while l touched this project. I’ll unlist it.
